### ISSUE TITLE
Can the code also be used with the ESP32?

### ISSUE THREAD

**Issue by eabase** [bblanchon/cpp4arduino#2]
We have an ESP32 solution based on the Freematics Esprit.  
Does your code also support ESP32?

**Comment by bblanchon** [comment]
Hi @eabase,

I didn't try to run the code on ESP32, but it should work.
Which project do you want to run?

Best Regards,
Benoit

**Comment by eabase** [comment]
Hi @bblanchon,

> Which project do you want to run?

I'm not sure what you mean, but were trying to use the [TinyGSM](https://github.com/vshymanskyy/TinyGSM) library **without WiFi**, and it's nearly impossible to not getting the firmware bloated with all sorts of WiFi related stuff, even if it is never used.

**Comment by ristomatti** [comment]
@eabase You should probably create an issue to Arduino for ESP32 repository instead. As a random follower of this repository, it appears to me that the purpose of this project is to teach C++ techniques useful in Arduino context which has very little to do with issues using a specific library on a specific platform...

**Comment by bblanchon** [comment]
Indeed, you seem to be in the wrong place @eabase. As @ristomatti, this repository contains the code samples for the site [cpp4arduino.com](https://cpp4arduino.com/), a blog to teach C++ for Arduino programmers.
